import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#0a1420] ${inter.className} overflow-hidden `}>
        {/* <div className="w-[20%] min-w-[185px] md:flex hidden h-screen bg-[#07101b] "></div>
        <div className=" text-white min-h-screen overflow-auto w-full lg:p-10 p-8"> */}
          {children}
        {/* </div> */}

      </body>
    </html>
  );
}
